//
// Generated file, do not edit! Created by nedtool 5.6 from src/AllTheWayMsg.msg.
//

#ifndef __ALLTHEWAYMSG_M_H
#define __ALLTHEWAYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/AllTheWayMsg.msg:4</tt> by nedtool.
 * <pre>
 * message AllTheWayMsg
 * {
 *     int id;
 *     int hops;
 * }
 * </pre>
 */
class AllTheWayMsg : public ::omnetpp::cMessage
{
  protected:
    int id;
    int hops;

  private:
    void copy(const AllTheWayMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AllTheWayMsg&);

  public:
    AllTheWayMsg(const char *name=nullptr, short kind=0);
    AllTheWayMsg(const AllTheWayMsg& other);
    virtual ~AllTheWayMsg();
    AllTheWayMsg& operator=(const AllTheWayMsg& other);
    virtual AllTheWayMsg *dup() const override {return new AllTheWayMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getHops() const;
    virtual void setHops(int hops);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AllTheWayMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AllTheWayMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ALLTHEWAYMSG_M_H

